Homework 1
neprotod/food-delivery-server-goit pull request #1
Opened 2019-11-02 03:55 UTC by neprotod

Привет. Я немного экспериментировал, насколько плох или хорошо такой подход с роутерами?

2019-11-05 09:31 UTC, odykyi commented on src/routers/signup.js
> +        });
add catch here

2019-11-05 09:34 UTC, odykyi commented on src/router.js
> +        return `There isn't router "${routName}" in application`;
res.end ?

2019-11-05 09:35 UTC, odykyi commented on src/routers/products.js
> +    });
catch

2019-11-05 09:39 UTC, odykyi commented on src/server.js
> +        const parseUrl = url.parse(req.url, true);
if url not parsed return error

2019-11-05 09:39 UTC, odykyi commented on src/server.js
> +            if(body)
use brackets

2019-11-05 09:40 UTC, odykyi commented on src/routers/signup.js
> +                users = JSON.parse(fs.readFileSync(filePath, 'utf8'));
do not use sync methods

2019-11-05 09:40 UTC, odykyi commented on src/routers/signup.js
> +            if(fs.existsSync(filePath)){
do not use sync methods

2019-11-05 10:28 UTC, neprotod commented on src/routers/signup.js
> +            if(fs.existsSync(filePath)){
> do not use sync methods
Так exists depricated
nodejs.org/dist/latest-v12.x/docs/api/fs.html#fs_fs_exists_path_callback

2019-11-06 08:26 UTC, odykyi commented on src/routers/signup.js
> +            if(fs.existsSync(filePath)){
@neprotod да он deprecated

юзай fs.stat

2019-11-06 08:26 UTC, odykyi commented on src/routers/products.js
> +    });
@neprotod add .cathc() to Promise

2019-11-06 08:29 UTC, odykyi commented
> Привет. Я немного экспериментировал, насколько плох или хорошо такой подход с роутерами?

можешь использовать такой подход

но он не слишком явный

2019-11-06 08:30 UTC, odykyi reviewed
нужно внести правки

2019-11-06 08:30 UTC, odykyi requested changes
нужно внести правки

2019-11-07 12:29 UTC, odykyi approved these changes

2019-11-07 12:33 UTC, merged